### ISSUE TITLE
Typescript Error: unmatched `)` in `vpython-jupyter/vpython/vpython_libraries/plotly.min.js`

### ISSUE THREAD

**Issue by KHALAK** [BruceSherwood/vpython-jupyter#53] opened 2018-08-05 00:04 UTC
There is an unmatched `)` in `vpython-jupyter/vpython/vpython_libraries/plotly.min.js` which gives a Typescript Error. Could you, please, look at it? It is spottable in the Firefox's Web Console (Ctrl + Shift + K) upon starting a notebook with enabled `vpython-jupyter` extension. Thank you in advance for maintaining this extension.

**Comment by BruceSherwood** [comment] 2018-08-05 14:40
I'm baffled. Chrome gives a bit more information than Firefox:
Invalid regular expression: /^rgb\(['\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*']\)$/: Unmatched ')'

I don't see an unmatched parenthesis in the expression above.

The console points to D  = new RegExp("^rgb\\(" + [E, E, E] + "\\)$"), which doesn't seem to have a parenthesis error, where E = "\\s*([+-]?\\d+)\\s*" also seems to have no parenthesis error. Moreover, the error is intermittent, at least on Chrome (maybe it's constant on Firefox?). I have no idea how to proceed.

**Comment by KHALAK** [comment] 2018-08-06 06:07
I would suggest upgrading to `plotly.min.js (= 1.39.4)` without investigating the issue.

**Comment by BruceSherwood** [comment] 2018-08-07 21:13
Good suggestion. I'll try that.

**Comment by jcoady** [comment] 2018-08-07 21:33
Try testing it with the following regular expression tester website. Maybe it can help you figure out what the problem is. 

https://regex101.com/ 

Also try google the words "regular expression javascript unmatched" for hints of how others may have solved similar problem with unmatched ')' . 

John

**Comment by jcoady** [comment] 2018-08-07 22:03
I tried the following in the regular expression tester and it matched the parenthesis 

^rgb(\['\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*'\])$ 

I replaced the first [ with \[ and the closing ] with \] . I don't know if this will solve your problem but you can try it out at to see if it gives you the functionality you want with the regular expression. 

John

**Comment by BruceSherwood** [comment] 2018-08-08 04:16
This is very strange. Even in the newest Plotly for JavaScript, ignoring the pretty printing of Chrome that converts \\ to \, the plotly library contains a large number of structures of the following kind:

E="\\s*([+-]?\\d+)\\s*"
D1=new RegExp("^rgb\\("+[E,E,E]+"\\)$")

The argument of RegExp looks like this (pretty printed to display \\ as \):
^rgb\(['\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*']\)$

Since the plotly library expects the form "rgb(r,g,b)", this RegExp expression seems to make no sense, since there are brackets where none would seem to be expected, and there are commas that are not strings. In fact, RegExp gives an error with this argument.

Compare with this argument for RegExp: "^rgb\\("+E+','+E+','+E+"\\)$")" which would yield "rgb(r,g,b)".

I'm again baffled as to how plotly works at all. I must be missing some arcane property of RegExp.

**Comment by jcoady** [comment] 2018-08-08 05:18
I think the problem has to do with the square brackets [ ] in 

D1=new RegExp("^rgb\("+[E,E,E]+"\)$") 

Try putting \ in front of the opening and closing square bracket. Change the above to 

D1=new RegExp("^rgb\("+\[E,E,E\]+"\)$") 

See if this change for the above line of code fixes the problem. 

John

**Comment by KHALAK** [comment] 2018-08-08 09:55
Symlinking non-minified `plotly.js` as `plotly.min.js` (itself mangled) might have provided a better way for debugging the issue, however, not. The issue is still here. I've tried the above suggestion putting `\` in front of the opening and closing square brackets in the indicated `plotly.js:15513` line with no change in behavior. The `plotly.js` principal developer might be of reference here.

**Comment by KHALAK** [comment] 2018-08-08 11:33
The same 'unmatched' error shows up on `jupyter-vega` extension, bzw.

**Comment by BruceSherwood** [comment] 2018-08-08 15:42
Consider the following JavaScript code:

```
var E="\\s*([+-]?\\d+)\\s*"
var F = "^rgb\\("+E+','+E+','+E+"\\)$"
var G = "^rgb\\("+[E,E,E]+"\\)$"
console.log(F)
console.log(G)
var D=new RegExp(F)
var m = 'rgb(1,2,3)'.match(D)
console.log(m[0])

```
This is the output, which is correct:

```
^rgb\(\s*([+-]?\d+)\s*,\s*([+-]?\d+)\s*,\s*([+-]?\d+)\s*\)$
^rgb\(['\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*', '\s*([+-]?\d+)\s*']\)$
rgb(1,2,3)
```
If instead I use RegExp(G) I get the error, and I get errors if I put
backslashes in front of the brackets, which doesn't surprise me,
because no variant of G is a legal JavaScript regular expression.

I'm left baffled as to how the very strange form G shows up in plotly.

**Comment by BruceSherwood** [comment] 2018-08-08 20:41
My analysis was correct. When I corrected those strange RegExp statements in plotly.min.js, the error messages went away in Jupyter VPython. I'll ask Matt Craig to build a new installer. Thanks, Khalak, for pointing out the problem.

**Comment by KHALAK** [comment] 2018-08-09 13:28
I've just tested the latest commits, and there is still at least one replacement needed, albeit it might be of a different pattern. It's being shown both, in Chrome and Firefox (it's only shows once upon starting the notebook, so, one needs to restart it to see if the errors are gone).

**Comment by BruceSherwood** [comment] 2018-08-09 15:53
Yes, sigh. I made a mistake and didn't update all the things I had to update. I'm working on it.

**Comment by KHALAK** [comment] 2018-08-10 08:42
Thank you for such elaborate dealing with quite unexpected bug in `plotly`, following your recent commit `vpython` fully works now.

**Comment by BruceSherwood** [comment] 2018-08-10 13:03
Thanks. And I also just now fixed long-standing bugs in the curve and points objects, so we'll make a new release soon.

**Closed by BruceSherwood** 2018-08-10 13:03 UTC
